export default {
  UPDATE_COLORS: 'UPDATE_COLORS',
  RESET_COLORS: 'RESET_COLORS',
  UPDATE_NAVBAR: 'UPDATE_NAVBAR',
  RESET_NAVBAR: 'RESET_NAVBAR',
  SLIDE_FORWARD: 'SLIDE_FORWARD',
  SLIDE_BACK: 'SLIDE_BACK',
  FETCH_TEMPLATE: 'FETCH_TEMPLATE'
}
